name: flutter_repository
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_zoom_drawer: ^3.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Eternal package 
  flutter_lints: ^2.0.1 # for developer toprovide me with clean code

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/card_images/

  # fonts:
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
          weight: 600
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
          weight: 500
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
          weight: 400

